CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE categorie (
    idcategorie integer GENERATED BY DEFAULT AS IDENTITY,
    nom character varying NOT NULL,
    description character varying,
    CONSTRAINT categorie_pkey PRIMARY KEY (idcategorie)
);

CREATE TABLE client (
    idclient integer GENERATED BY DEFAULT AS IDENTITY,
    nom character varying NOT NULL,
    email character varying,
    telephone character varying,
    adresse character varying,
    CONSTRAINT client_pkey PRIMARY KEY (idclient)
);

CREATE TABLE fournisseur (
    idfournisseur integer GENERATED BY DEFAULT AS IDENTITY,
    nom character varying NOT NULL,
    email character varying,
    telephone character varying,
    CONSTRAINT fournisseur_pkey PRIMARY KEY (idfournisseur)
);

CREATE TABLE menu (
    idmenu integer GENERATED BY DEFAULT AS IDENTITY,
    titre character varying NOT NULL,
    description character varying NOT NULL,
    mem_routerlink character varying NOT NULL,
    mem_href character varying NOT NULL,
    mem_icon character varying NOT NULL,
    mem_target character varying NOT NULL,
    hassubmenu boolean,
    parentid integer,
    CONSTRAINT menu_pkey PRIMARY KEY (idmenu),
    CONSTRAINT menu_parentid_fkey FOREIGN KEY (parentid) REFERENCES menu (idmenu) ON DELETE CASCADE
);

CREATE TABLE profile (
    idprofil integer GENERATED BY DEFAULT AS IDENTITY,
    nom character varying NOT NULL,
    description character varying NOT NULL,
    CONSTRAINT pk_profile PRIMARY KEY (idprofil)
);

CREATE TABLE article (
    idarticle integer GENERATED BY DEFAULT AS IDENTITY,
    nom character varying NOT NULL,
    description character varying,
    prix numeric(18,2) NOT NULL,
    quantitestock integer NOT NULL,
    seuilminimum integer NOT NULL,
    sexe character varying(30),
    typevetement character varying(50),
    marque character varying(80),
    couleur character varying(50),
    taille character varying(20),
    idcategorie integer,
    CONSTRAINT article_pkey PRIMARY KEY (idarticle),
    CONSTRAINT article_idcategorie_fkey FOREIGN KEY (idcategorie) REFERENCES categorie (idcategorie) ON DELETE SET NULL
);

CREATE TABLE commande (
    idcommande integer GENERATED BY DEFAULT AS IDENTITY,
    datecommande timestamp without time zone NOT NULL,
    idclient integer NOT NULL,
    totalcommande numeric(18,2) NOT NULL,
    statut character varying NOT NULL,
    CONSTRAINT commande_pkey PRIMARY KEY (idcommande),
    CONSTRAINT commande_idclient_fkey FOREIGN KEY (idclient) REFERENCES client (idclient) ON DELETE CASCADE
);

CREATE TABLE roles (
    idrole integer GENERATED BY DEFAULT AS IDENTITY,
    nom character varying NOT NULL,
    description character varying NOT NULL,
    idprofile integer,
    idroleparent integer,
    CONSTRAINT roles_pkey PRIMARY KEY (idrole),
    CONSTRAINT roles_idprofile_fkey FOREIGN KEY (idprofile) REFERENCES profile (idprofil) ON DELETE CASCADE,
    CONSTRAINT roles_idroleparent_fkey FOREIGN KEY (idroleparent) REFERENCES roles (idrole) ON DELETE CASCADE
);

CREATE TABLE article_fournisseur (
    idarticle integer NOT NULL,
    idfournisseur integer NOT NULL,
    CONSTRAINT article_fournisseur_pkey PRIMARY KEY (idarticle, idfournisseur),
    CONSTRAINT article_fournisseur_idarticle_fkey FOREIGN KEY (idarticle) REFERENCES article (idarticle) ON DELETE CASCADE,
    CONSTRAINT article_fournisseur_idfournisseur_fkey FOREIGN KEY (idfournisseur) REFERENCES fournisseur (idfournisseur) ON DELETE CASCADE
);

CREATE TABLE facture (
    idfacture integer GENERATED BY DEFAULT AS IDENTITY,
    idcommande integer NOT NULL,
    datefacture timestamp without time zone NOT NULL,
    montantttc numeric(18,2) NOT NULL,
    statut character varying NOT NULL,
    CONSTRAINT facture_pkey PRIMARY KEY (idfacture),
    CONSTRAINT facture_idcommande_fkey FOREIGN KEY (idcommande) REFERENCES commande (idcommande) ON DELETE CASCADE
);

CREATE TABLE ligne_commande (
    idlignecommande integer GENERATED BY DEFAULT AS IDENTITY,
    idcommande integer NOT NULL,
    idarticle integer NOT NULL,
    quantite integer NOT NULL,
    prixunitaire numeric(18,2) NOT NULL,
    montantligne numeric(18,2) NOT NULL,
    CONSTRAINT ligne_commande_pkey PRIMARY KEY (idlignecommande),
    CONSTRAINT ligne_commande_idarticle_fkey FOREIGN KEY (idarticle) REFERENCES article (idarticle) ON DELETE CASCADE,
    CONSTRAINT ligne_commande_idcommande_fkey FOREIGN KEY (idcommande) REFERENCES commande (idcommande) ON DELETE CASCADE
);

CREATE TABLE livraison (
    idlivraison integer GENERATED BY DEFAULT AS IDENTITY,
    idcommande integer NOT NULL,
    datelivraison timestamp without time zone NOT NULL,
    adresse character varying,
    statut character varying NOT NULL,
    CONSTRAINT livraison_pkey PRIMARY KEY (idlivraison),
    CONSTRAINT livraison_idcommande_fkey FOREIGN KEY (idcommande) REFERENCES commande (idcommande) ON DELETE CASCADE
);

CREATE TABLE lstmenu (
    idrole integer NOT NULL,
    idmenu integer NOT NULL,
    CONSTRAINT pk_lst PRIMARY KEY (idrole, idmenu),
    CONSTRAINT lstmenu_idmenu_fkey FOREIGN KEY (idmenu) REFERENCES menu (idmenu) ON DELETE CASCADE,
    CONSTRAINT lstmenu_idrole_fkey FOREIGN KEY (idrole) REFERENCES roles (idrole) ON DELETE CASCADE
);

CREATE TABLE utilisateur (
    iduser integer GENERATED BY DEFAULT AS IDENTITY,
    nom character varying NOT NULL,
    username character varying NOT NULL,
    motpass character varying NOT NULL,
    email character varying NOT NULL,
    telephone character varying NOT NULL,
    idrole integer,
    CONSTRAINT utilisateur_pkey PRIMARY KEY (iduser),
    CONSTRAINT utilisateur_idrole_fkey FOREIGN KEY (idrole) REFERENCES roles (idrole) ON DELETE CASCADE
);

CREATE TABLE paiement (
    idpaiement integer GENERATED BY DEFAULT AS IDENTITY,
    idfacture integer NOT NULL,
    datepaiement timestamp without time zone NOT NULL,
    montant numeric(18,2) NOT NULL,
    modepaiement character varying,
    reference character varying,
    CONSTRAINT paiement_pkey PRIMARY KEY (idpaiement),
    CONSTRAINT paiement_idfacture_fkey FOREIGN KEY (idfacture) REFERENCES facture (idfacture) ON DELETE CASCADE
);

CREATE TABLE refreshtoken (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    token character varying NOT NULL,
    expiresatutc timestamp without time zone,
    revoked boolean,
    iduser integer,
    CONSTRAINT refreshtoken_pkey PRIMARY KEY (id),
    CONSTRAINT refreshtoken_iduser_fkey FOREIGN KEY (iduser) REFERENCES utilisateur (iduser)
);

CREATE INDEX "IX_article_idcategorie" ON article (idcategorie);

CREATE INDEX "IX_article_fournisseur_idfournisseur" ON article_fournisseur (idfournisseur);

CREATE UNIQUE INDEX categorie_nom_key ON categorie (nom);

CREATE UNIQUE INDEX client_email_key ON client (email);

CREATE INDEX "IX_commande_idclient" ON commande (idclient);

CREATE UNIQUE INDEX facture_idcommande_key ON facture (idcommande);

CREATE INDEX "IX_ligne_commande_idarticle" ON ligne_commande (idarticle);

CREATE UNIQUE INDEX ligne_commande_idcommande_idarticle_key ON ligne_commande (idcommande, idarticle);

CREATE UNIQUE INDEX livraison_idcommande_key ON livraison (idcommande);

CREATE INDEX "IX_lstmenu_idmenu" ON lstmenu (idmenu);

CREATE INDEX "IX_menu_parentid" ON menu (parentid);

CREATE INDEX "IX_paiement_idfacture" ON paiement (idfacture);

CREATE INDEX "IX_refreshtoken_iduser" ON refreshtoken (iduser);

CREATE INDEX "IX_roles_idprofile" ON roles (idprofile);

CREATE INDEX "IX_roles_idroleparent" ON roles (idroleparent);

CREATE INDEX "IX_utilisateur_idrole" ON utilisateur (idrole);

CREATE UNIQUE INDEX utilisateur_email_key ON utilisateur (email);

CREATE UNIQUE INDEX utilisateur_username_key ON utilisateur (username);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260429083318_AddArticleAttributes', '8.0.18');

COMMIT;

