// <auto-generated />
using System;
using Core.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(IAMDbContext))]
    partial class IAMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Article", b =>
                {
                    b.Property<int>("Idarticle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idarticle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idarticle"));

                    b.Property<string>("Couleur")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("couleur");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<int?>("Idcategorie")
                        .HasColumnType("integer")
                        .HasColumnName("idcategorie");

                    b.Property<string>("Marque")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("marque");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nom");

                    b.Property<decimal>("Prix")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prix");

                    b.Property<int>("Quantitestock")
                        .HasColumnType("integer")
                        .HasColumnName("quantitestock");

                    b.Property<int>("Seuilminimum")
                        .HasColumnType("integer")
                        .HasColumnName("seuilminimum");

                    b.Property<string>("Sexe")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sexe");

                    b.Property<string>("Taille")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("taille");

                    b.Property<string>("Typevetement")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("typevetement");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("imageurl");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<string>("Statut")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("statut")
                        .HasDefaultValue("Actif");

                    b.Property<string>("Slug")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("isfeatured")
                        .HasDefaultValue(false);

                    b.Property<string>("Matiere")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("matiere");

                    b.HasKey("Idarticle")
                        .HasName("article_pkey");

                    b.HasIndex("Idcategorie");

                    b.ToTable("article", (string)null);
                });

            modelBuilder.Entity("Core.Entities.ArticleFournisseur", b =>
                {
                    b.Property<int>("Idarticle")
                        .HasColumnType("integer")
                        .HasColumnName("idarticle");

                    b.Property<int>("Idfournisseur")
                        .HasColumnType("integer")
                        .HasColumnName("idfournisseur");

                    b.HasKey("Idarticle", "Idfournisseur")
                        .HasName("article_fournisseur_pkey");

                    b.HasIndex("Idfournisseur");

                    b.ToTable("article_fournisseur", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Categorie", b =>
                {
                    b.Property<int>("Idcategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcategorie");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcategorie"));

                        b.Property<string>("Couleur")
                            .HasMaxLength(50)
                            .HasColumnType("character varying(50)")
                            .HasColumnName("couleur");

                    b.Property<string>("Description")
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nom");

                        b.Property<string>("Sexe")
                            .HasMaxLength(30)
                            .HasColumnType("character varying(30)")
                            .HasColumnName("sexe");

                        b.Property<string>("Typevetement")
                            .HasMaxLength(50)
                            .HasColumnType("character varying(50)")
                            .HasColumnName("typevetement");

                    b.HasKey("Idcategorie")
                        .HasName("categorie_pkey");

                    b.HasIndex(new[] { "Nom" }, "categorie_nom_key")
                        .IsUnique();

                    b.ToTable("categorie", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Client", b =>
                {
                    b.Property<int>("Idclient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idclient");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idclient"));

                    b.Property<string>("Adresse")
                        .HasColumnType("character varying")
                        .HasColumnName("adresse");

                    b.Property<string>("Email")
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nom");

                    b.Property<string>("Telephone")
                        .HasColumnType("character varying")
                        .HasColumnName("telephone");

                    b.HasKey("Idclient")
                        .HasName("client_pkey");

                    b.HasIndex(new[] { "Email" }, "client_email_key")
                        .IsUnique();

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Commande", b =>
                {
                    b.Property<int>("Idcommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcommande");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcommande"));

                    b.Property<DateTime>("Datecommande")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datecommande");

                    b.Property<int>("Idclient")
                        .HasColumnType("integer")
                        .HasColumnName("idclient");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("statut");

                    b.Property<decimal>("Totalcommande")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("totalcommande");

                    b.HasKey("Idcommande")
                        .HasName("commande_pkey");

                    b.HasIndex("Idclient");

                    b.ToTable("commande", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Facture", b =>
                {
                    b.Property<int>("Idfacture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idfacture");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idfacture"));

                    b.Property<DateTime>("Datefacture")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datefacture");

                    b.Property<int>("Idcommande")
                        .HasColumnType("integer")
                        .HasColumnName("idcommande");

                    b.Property<decimal>("Montantttc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("montantttc");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("statut");

                    b.HasKey("Idfacture")
                        .HasName("facture_pkey");

                    b.HasIndex(new[] { "Idcommande" }, "facture_idcommande_key")
                        .IsUnique();

                    b.ToTable("facture", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Fournisseur", b =>
                {
                    b.Property<int>("Idfournisseur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idfournisseur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idfournisseur"));

                    b.Property<string>("Email")
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nom");

                    b.Property<string>("Telephone")
                        .HasColumnType("character varying")
                        .HasColumnName("telephone");

                    b.HasKey("Idfournisseur")
                        .HasName("fournisseur_pkey");

                    b.ToTable("fournisseur", (string)null);
                });

            modelBuilder.Entity("Core.Entities.LigneCommande", b =>
                {
                    b.Property<int>("Idlignecommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idlignecommande");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idlignecommande"));

                    b.Property<int>("Idarticle")
                        .HasColumnType("integer")
                        .HasColumnName("idarticle");

                    b.Property<int>("Idcommande")
                        .HasColumnType("integer")
                        .HasColumnName("idcommande");

                    b.Property<decimal>("Montantligne")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("montantligne");

                    b.Property<decimal>("Prixunitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prixunitaire");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer")
                        .HasColumnName("quantite");

                    b.HasKey("Idlignecommande")
                        .HasName("ligne_commande_pkey");

                    b.HasIndex("Idarticle");

                    b.HasIndex(new[] { "Idcommande", "Idarticle" }, "ligne_commande_idcommande_idarticle_key")
                        .IsUnique();

                    b.ToTable("ligne_commande", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Livraison", b =>
                {
                    b.Property<int>("Idlivraison")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idlivraison");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idlivraison"));

                    b.Property<string>("Adresse")
                        .HasColumnType("character varying")
                        .HasColumnName("adresse");

                    b.Property<DateTime>("Datelivraison")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datelivraison");

                    b.Property<int>("Idcommande")
                        .HasColumnType("integer")
                        .HasColumnName("idcommande");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("statut");

                    b.HasKey("Idlivraison")
                        .HasName("livraison_pkey");

                    b.HasIndex(new[] { "Idcommande" }, "livraison_idcommande_key")
                        .IsUnique();

                    b.ToTable("livraison", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Menu", b =>
                {
                    b.Property<int>("Idmenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idmenu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idmenu"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<bool?>("Hassubmenu")
                        .HasColumnType("boolean")
                        .HasColumnName("hassubmenu");

                    b.Property<string>("MemHref")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("mem_href");

                    b.Property<string>("MemIcon")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("mem_icon");

                    b.Property<string>("MemRouterlink")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("mem_routerlink");

                    b.Property<string>("MemTarget")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("mem_target");

                    b.Property<int?>("Parentid")
                        .HasColumnType("integer")
                        .HasColumnName("parentid");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("titre");

                    b.HasKey("Idmenu")
                        .HasName("menu_pkey");

                    b.HasIndex("Parentid");

                    b.ToTable("menu", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Paiement", b =>
                {
                    b.Property<int>("Idpaiement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idpaiement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idpaiement"));

                    b.Property<DateTime>("Datepaiement")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("datepaiement");

                    b.Property<int>("Idfacture")
                        .HasColumnType("integer")
                        .HasColumnName("idfacture");

                    b.Property<string>("Modepaiement")
                        .HasColumnType("character varying")
                        .HasColumnName("modepaiement");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("montant");

                    b.Property<string>("Reference")
                        .HasColumnType("character varying")
                        .HasColumnName("reference");

                    b.HasKey("Idpaiement")
                        .HasName("paiement_pkey");

                    b.HasIndex("Idfacture");

                    b.ToTable("paiement", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Profile", b =>
                {
                    b.Property<int>("Idprofil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idprofil");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idprofil"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nom");

                    b.HasKey("Idprofil")
                        .HasName("pk_profile");

                    b.ToTable("profile", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Refreshtoken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Expiresatutc")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiresatutc");

                    b.Property<int?>("Iduser")
                        .HasColumnType("integer")
                        .HasColumnName("iduser");

                    b.Property<bool?>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("refreshtoken_pkey");

                    b.HasIndex("Iduser");

                    b.ToTable("refreshtoken", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Role", b =>
                {
                    b.Property<int>("Idrole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idrole");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idrole"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("description");

                    b.Property<int?>("Idprofile")
                        .HasColumnType("integer")
                        .HasColumnName("idprofile");

                    b.Property<int?>("Idroleparent")
                        .HasColumnType("integer")
                        .HasColumnName("idroleparent");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nom");

                    b.HasKey("Idrole")
                        .HasName("roles_pkey");

                    b.HasIndex("Idprofile");

                    b.HasIndex("Idroleparent");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Iduser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iduser");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Iduser"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("email");

                    b.Property<int?>("Idrole")
                        .HasColumnType("integer")
                        .HasColumnName("idrole");

                    b.Property<string>("Motpass")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("motpass");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("nom");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("telephone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("username");

                    b.HasKey("Iduser")
                        .HasName("utilisateur_pkey");

                    b.HasIndex("Idrole");

                    b.HasIndex(new[] { "Email" }, "utilisateur_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "utilisateur_username_key")
                        .IsUnique();

                    b.ToTable("utilisateur", (string)null);
                });

            modelBuilder.Entity("Lstmenu", b =>
                {
                    b.Property<int>("Idrole")
                        .HasColumnType("integer")
                        .HasColumnName("idrole");

                    b.Property<int>("Idmenu")
                        .HasColumnType("integer")
                        .HasColumnName("idmenu");

                    b.HasKey("Idrole", "Idmenu")
                        .HasName("pk_lst");

                    b.HasIndex("Idmenu");

                    b.ToTable("lstmenu", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Article", b =>
                {
                    b.HasOne("Core.Entities.Categorie", "IdcategorieNavigation")
                        .WithMany("Articles")
                        .HasForeignKey("Idcategorie")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("article_idcategorie_fkey");

                    b.Navigation("IdcategorieNavigation");
                });

            modelBuilder.Entity("Core.Entities.ArticleFournisseur", b =>
                {
                    b.HasOne("Core.Entities.Article", "IdarticleNavigation")
                        .WithMany("ArticleFournisseurs")
                        .HasForeignKey("Idarticle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("article_fournisseur_idarticle_fkey");

                    b.HasOne("Core.Entities.Fournisseur", "IdfournisseurNavigation")
                        .WithMany("ArticleFournisseurs")
                        .HasForeignKey("Idfournisseur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("article_fournisseur_idfournisseur_fkey");

                    b.Navigation("IdarticleNavigation");

                    b.Navigation("IdfournisseurNavigation");
                });

            modelBuilder.Entity("Core.Entities.Commande", b =>
                {
                    b.HasOne("Core.Entities.Client", "IdclientNavigation")
                        .WithMany("Commandes")
                        .HasForeignKey("Idclient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("commande_idclient_fkey");

                    b.Navigation("IdclientNavigation");
                });

            modelBuilder.Entity("Core.Entities.Facture", b =>
                {
                    b.HasOne("Core.Entities.Commande", "IdcommandeNavigation")
                        .WithMany("Factures")
                        .HasForeignKey("Idcommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("facture_idcommande_fkey");

                    b.Navigation("IdcommandeNavigation");
                });

            modelBuilder.Entity("Core.Entities.LigneCommande", b =>
                {
                    b.HasOne("Core.Entities.Article", "IdarticleNavigation")
                        .WithMany()
                        .HasForeignKey("Idarticle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ligne_commande_idarticle_fkey");

                    b.HasOne("Core.Entities.Commande", "IdcommandeNavigation")
                        .WithMany("LigneCommandes")
                        .HasForeignKey("Idcommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("ligne_commande_idcommande_fkey");

                    b.Navigation("IdarticleNavigation");

                    b.Navigation("IdcommandeNavigation");
                });

            modelBuilder.Entity("Core.Entities.Livraison", b =>
                {
                    b.HasOne("Core.Entities.Commande", "IdcommandeNavigation")
                        .WithMany("Livraisons")
                        .HasForeignKey("Idcommande")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("livraison_idcommande_fkey");

                    b.Navigation("IdcommandeNavigation");
                });

            modelBuilder.Entity("Core.Entities.Menu", b =>
                {
                    b.HasOne("Core.Entities.Menu", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("Parentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("menu_parentid_fkey");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Core.Entities.Paiement", b =>
                {
                    b.HasOne("Core.Entities.Facture", "IdfactureNavigation")
                        .WithMany("Paiements")
                        .HasForeignKey("Idfacture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("paiement_idfacture_fkey");

                    b.Navigation("IdfactureNavigation");
                });

            modelBuilder.Entity("Core.Entities.Refreshtoken", b =>
                {
                    b.HasOne("Core.Entities.Utilisateur", "IduserNavigation")
                        .WithMany("Refreshtokens")
                        .HasForeignKey("Iduser")
                        .HasConstraintName("refreshtoken_iduser_fkey");

                    b.Navigation("IduserNavigation");
                });

            modelBuilder.Entity("Core.Entities.Role", b =>
                {
                    b.HasOne("Core.Entities.Profile", "IdprofileNavigation")
                        .WithMany("Roles")
                        .HasForeignKey("Idprofile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("roles_idprofile_fkey");

                    b.HasOne("Core.Entities.Role", "IdroleparentNavigation")
                        .WithMany("InverseIdroleparentNavigation")
                        .HasForeignKey("Idroleparent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("roles_idroleparent_fkey");

                    b.Navigation("IdprofileNavigation");

                    b.Navigation("IdroleparentNavigation");
                });

            modelBuilder.Entity("Core.Entities.Utilisateur", b =>
                {
                    b.HasOne("Core.Entities.Role", "IdroleNavigation")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("Idrole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("utilisateur_idrole_fkey");

                    b.Navigation("IdroleNavigation");
                });

            modelBuilder.Entity("Lstmenu", b =>
                {
                    b.HasOne("Core.Entities.Menu", null)
                        .WithMany()
                        .HasForeignKey("Idmenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lstmenu_idmenu_fkey");

                    b.HasOne("Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("Idrole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("lstmenu_idrole_fkey");
                });

            modelBuilder.Entity("Core.Entities.Article", b =>
                {
                    b.Navigation("ArticleFournisseurs");
                });

            modelBuilder.Entity("Core.Entities.Categorie", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Core.Entities.Client", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("Core.Entities.Commande", b =>
                {
                    b.Navigation("Factures");

                    b.Navigation("LigneCommandes");

                    b.Navigation("Livraisons");
                });

            modelBuilder.Entity("Core.Entities.Facture", b =>
                {
                    b.Navigation("Paiements");
                });

            modelBuilder.Entity("Core.Entities.Fournisseur", b =>
                {
                    b.Navigation("ArticleFournisseurs");
                });

            modelBuilder.Entity("Core.Entities.Menu", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("Core.Entities.Profile", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Core.Entities.Role", b =>
                {
                    b.Navigation("InverseIdroleparentNavigation");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("Core.Entities.Utilisateur", b =>
                {
                    b.Navigation("Refreshtokens");
                });
#pragma warning restore 612, 618
        }
    }
}
